### ISSUE TITLE
chore/buildings schema

### ISSUE THREAD

**Issue by czaja307** [Solvro/backend-topwr#10]

**Comment by karolwolek** [comment]
![Image](https://github.com/user-attachments/assets/5184bad0-5dcb-4fe7-8629-a87aaf35267c)
This is building table schema diagram. 
* Not sure about the address if its sufficient and if the seperate table is not an overkill for that.
* The campus table could be useful in the future for building filtration as it is done on https://pwr.edu.pl/uczelnia/mapa-kampusu

Let me know if it meets the mobile criteria

**Comment by czaja307** [comment]
@simon-the-shark waiting for your insight

**Comment by simon-the-shark** [comment]
From the mobile side it looks fine. We're still not sure if we'll use the have food, but at worst we'll just delete this prop - no problem here.


The campus is not used at the moment, but it's imo a nice info to store for the future. 


From the backend side, imo the address could just be 2 fields, the autogenerated panel admin will have easier job to do too

**Comment by czaja307** [comment]
> * Not sure about the address if its sufficient and if the seperate table is not an overkill for that.

can't tell you about the first part, but for the second - imo it is overkill
you don't get any benefits from using second table and the access time increases as you need to join both tables to get full data

one more note i would suggest to change enum name from `icon_type` to `building_icon_type` -enum types in postreSQL must have unique names and we need to keep in mind that our service will be quite big after some time

**Comment by karolwolek** [comment]
you mean to change the type ICON that is an enum ? Because speaking about about the field icon_type i think it can stay as it is.
![Image](https://github.com/user-attachments/assets/f5d9e347-d538-4a3e-9b0b-4c8d198d5d94)

**Comment by czaja307** [comment]
oops, great catch!

yeah, the field name is absolutely okay - i was talking about enum name as you pointed

**Comment by karolwolek** [comment]
I updated  the diagram and provided the source in json
