### ISSUE TITLE
chore/academic calendar schema

### ISSUE THREAD

**Issue by czaja307** [Solvro/backend-topwr#11]

**Comment by mateusz-plaska** [comment]
![Image](https://github.com/user-attachments/assets/54b47397-761e-400c-92ff-c641550deefb)

This is db schema for academic calendar. I have added two extra tables which are not currently in existing model. I think tables "holidays" and "events" might be useful in the future but that is only my suggestion.

**Comment by czaja307** [comment]
here are some comments:
1. I prefer using text over varchars whenever possible, when using postgreSQL(https://stackoverflow.com/questions/4848964/difference-between-text-and-varchar-character-varying)
2. I'm not a fan of storing recurring holidays this way - either omit it and store new instance in every calendar (personally i'd go with this one) or create new table with recurring holidays
3. Events calendar is scope of another task #3 (it needs some more discussion so leave it or now - you can post the current events table there for future reference)

**Comment by mateusz-plaska** [comment]
![Image](https://github.com/user-attachments/assets/247f1edf-38e2-4c73-931d-765cb1718a69)

Right, here is the corrected schema - without 'current events' table. 
Should I add this table to the schema? And if so, how should it look like (id, academic_calendar_id, event_id - taken this from the 'events calendar' table of another task)? 
But will this table be necessary and useful for us?

**Comment by czaja307** [comment]
Schema looks good, great job!
When it comes to `events` table you can add your version of it as-is into the #3 - it's a solid starting point for that task, which comes later in our roadmap.
