### ISSUE TITLE
feat/photo storage setup

### ISSUE THREAD

**Issue by czaja307** [Solvro/backend-topwr#16]
setup storage for photos and files

some self-hosted solution indicated by @simon-the-shark:
https://github.com/ahmadarif/adonis-drive-minio/blob/master/instructions.md

**Comment by simon-the-shark** [comment]
Ps. This is a random link from Google, do a proper research first

**Comment by czaja307** [comment]
will do, i'm just saving some random links that may turn out to be useful in the future :p
