### ISSUE TITLE
chore/faq sections schema

### ISSUE THREAD

**Issue by czaja307** [Solvro/backend-topwr#19]

**Comment by Matistan** [comment]
![Image](https://github.com/user-attachments/assets/21e28b6c-5274-45e3-852b-a1c7c28d7196)

this is my take on the faq db schema (I think it's supposed to be something like this)

**Comment by czaja307** [comment]
dw, it's a solid start
here are some comments:
1. as for now we have only one image per section and author - @simon-the-shark do you think we can extend this to multiple?
2. afaik, the autor is responsible for the whole FAQ section, but there can be also be multiple authors connected to section - @simon-the-shark correct me if i'm talking nonsense
3. the authors that you made looks cool but some more notes about it:
3.1. we will have to create one shared tables for social links with contributors, departments and organisations (i'll be coordinating this one so you can leave it as is by now)
3.2. what are `authors_subtitles` table for? (i'm not saying that's it bad - i just don't get what you meant by it)

**Comment by Matistan** [comment]
![Image](https://github.com/user-attachments/assets/69d731e6-9b1e-414f-b13a-4dd80b9c743e)
that's what I meant by subtitle 😅

so there should only be an author for the whole section, and not authors for each question?

**Comment by czaja307** [comment]
okay, it makes sense to me then
@simon-the-shark we need some answers xD

**Comment by simon-the-shark** [comment]
1. let's rename the faq sections and faq to some better names cause the one in Directus has caused issues multiple times. Imo e.g. GuideArticle and GuideQuestion is much clearer.
2. image is only one per whole section, not planning on changing that
3. tbh originally the authors were meant to be just a text field or list of strings connected to the whole section/article
4. Your other team member has already created "Contributors"  tables which is the same. My only note is that in theory relationship may be useful but it forces on us that all the author's are in a Team section. Not a problem now, but tbh I don't really like hard limitation like that.
5. apart from authors, we want "redactors" too in similar manner.

**Comment by czaja307** [comment]
> 3. tbh originally the authors were meant to be just a text field or list of strings connected to the whole section/article
> 4. Your other team member has already created "Contributors"  tables which is the same. My only note is that in theory relationship may be useful but it forces on us that all the author's are in a Team section. Not a problem now, but tbh I don't really like hard limitation like that.
> 5. apart from authors, we want "redactors" too in similar manner.


I think that separate table, something like guideAuthors is a good solution. We would have the separate tables, so it would be easy to make different sections for team and content creators (and also not a big deal if we would like to show them together). It also allows us to store both redactors and authors together. What do you think about it @simon-the-shark.

**Comment by simon-the-shark** [comment]
Okey for me but condiser that at the moment we're only planning to show only the names and nothing else so not really sure if we need separate table for authors at all

**Comment by simon-the-shark** [comment]
But you can do it, as long as it will be acceptable on the admin panel. My only note here is that we're not planning on using anything more than the authors names

**Comment by Matistan** [comment]
Ok, so I have a few questions:

- should there be a list of authors/redactors for each article, or just a single one?
- should there be authors/redactors for each question as well?

**Comment by czaja307** [comment]
From what I know there can be multiple authors/redactors for each article and questions do not have authors/redactors specified (they are made by the creators of the whole article)

**Comment by simon-the-shark** [comment]
1. Assume there might be multiple authors and multiple redactors for each section.

2. We assiosiate authors with section, not specific questions

**Comment by Matistan** [comment]
![Image](https://github.com/user-attachments/assets/71cb3cf1-329e-4972-8b1a-d429c74f5950)
Please check if this is what you meant

**Comment by czaja307** [comment]
1. As there will not be multiple images for one article, you can simply store image path as text in the `GuideArticles`
2. I'm not sure what is the convention of marking multiplicity in the tool that you are using, but you definitely need to have oneToMany relation between `GuideArticleQuestions` and `GuideQuestions`
3. I strongly discourage using different name than `id` for default PK
4. The way you did authors looks quite suboptimal to me. I think that you should use one table between authors and articles that would contain author_id, article_id and guide_author_role as enum

**Comment by Matistan** [comment]
![Image](https://github.com/user-attachments/assets/1c78f99c-0cc6-4ba6-8569-e1355abf917b)
aight, here's the version with everything applied

**Comment by czaja307** [comment]
I missed it before but actually there is no need for guideArticleQuestion, because every question is connected to only one article. Thus you can simply put article_id in GuideQuestions table and omit GuideArticleQuestions table.

**Comment by czaja307** [comment]
looks solid, good job
