### ISSUE TITLE
chore/prepare db schemas for cms models

### ISSUE THREAD

**Issue by czaja307** [Solvro/backend-topwr#2]
that's the beginning of the journey with moving to our custom backend from directus

i see this task like this:
1. look at the existing model in the https://admin.topwr.solvro.pl/
2. think about ways of improving or extending it (connected data that might be useful in the future and we can relatively easily obtain)
3. prepare schema in drawdb.app (or anything else that you like to use)

**Comment by czaja307** [comment]
about us needs tags for team indicating different versions of app they worked on

**Comment by czaja307** [comment]
buildings should include tag indicating the type of icon that should be used on the map

**Comment by simon-the-shark** [comment]
Authors and redactors*

**Comment by mini-bomba** [comment]
Here's my take on the authors/contributors & changelogs schemas:
![Exported diagram](https://github.com/user-attachments/assets/57740f38-ddf8-4b73-8390-85683014d6ea)
[Source file](https://github.com/user-attachments/files/17788225/ToPWR.contributors.changelogs.schema_2024-11-16T23_13_45.533Z.ddb.json)

**Comment by karolwolek** [comment]
I can make the buildings diagram, will do it tommorow

**Comment by czaja307** [comment]
@Solvro/topwr-backend please pick what you want to do and write it down here

**Comment by czaja307** [comment]
> Here's my take on the authors/contributors & changelogs schemas: ![Exported diagram](https://github.com/user-attachments/assets/57740f38-ddf8-4b73-8390-85683014d6ea) [Source file](https://github.com/user-attachments/files/17788225/ToPWR.contributors.changelogs.schema_2024-11-16T23_13_45.533Z.ddb.json)

looks pretty good for me
personally i'd go with enums but extra tables are also okay (i think you can even omit the id, because the name fields will have unique value)
also i'm a big fan of using text over varchar (but this is also personal preference) - but if you want to know why i think this thread on stack sums it up quite good https://stackoverflow.com/questions/4848964/difference-between-text-and-varchar-character-varying
when it comes to photos i think some kind of url/path is what we'll need

@simon-the-shark and @mikolaj-jalocha can also give some feedback from the mobile side

**Comment by mateusz-plaska** [comment]
I can make the academic calendar with swap of days.

**Comment by simon-the-shark** [comment]
> > Here's my take on the authors/contributors & changelogs schemas: ![Exported diagram](https://github.com/user-attachments/assets/57740f38-ddf8-4b73-8390-85683014d6ea) [Source file](https://github.com/user-attachments/files/17788225/ToPWR.contributors.changelogs.schema_2024-11-16T23_13_45.533Z.ddb.json)
> 
> looks pretty good for me personally i'd go with enums but extra tables are also okay (i think you can even omit the id, because the name fields will have unique value) also i'm a big fan of using text over varchar (but this is also personal preference) - but if you want to know why i think this thread on stack sums it up quite good https://stackoverflow.com/questions/4848964/difference-between-text-and-varchar-character-varying when it comes to photos i think some kind of url/path is what we'll need
> 
> [@simon-the-shark](https://github.com/simon-the-shark) and [@mikolaj-jalocha](https://github.com/mikolaj-jalocha) can also give some feedback from the mobile side

# Intro
So in general this is pretty nicely created db schema, but I think it's a bit off-synced with what we have on the mobile side (aka reality requirements are in some places different).

I think we can discuss few things from here on the mobile weekly still, but this are my purely invidual thoughts:

# Photos
About the photos: not sure how you usually handle this on adonis, but speaking from the django expierence, you would prolly want to have some custom storage service like minio set up: https://github.com/minio/minio and connect to it. Not sure if adonis and any potencial admin panels support this nicely (django does :P)? On the mobile side we want just URLs, but the admin panel or something should handle the bucket/storage uploads.

# Link types
1. At the moment we detect link types on the mobile side using regex, and have custom icons and custom order for them (different order in about us and different in sci clubs/departments) - so we can still do it this way as it's ready, but if you prefer, then you can take this to the backend side too (this prolly belongs to backend more). So taking this into account, enum for this case is enough, as we'll need to add icons etc on the mobile side and push an update to the stores anyway, so this will be quite a change and adding new enum value in migrations is prolly not that hard - correct me if I'm wrong. 
2. Link types as separate table only makes sense if we have svg icon field or something for it, then we could do this fully dynamically on the mobile - but we have to discuss with the mobile team if we want to use online icons (they'll load a bit slower, but I guess we can use some cache). So here we need to discuss if this is something we want to go for or not

_[MOBILE TEAM DISCUSSION NEEDED]: online svg icons and dynamic icon types_


# Contributors
1. Multiple links of the same type for one contributor - I don't think any situation like this exists at the moment, but it would be nice to handle this to be future-proof (changing this later can be actually quite nasty imo)
6. Tbh, roles/titles as just strings are enough for the mobile side. If you want to do this "nicer", then I guess you can, but I would check if this doesn't break the UX of some auto generated admin panels and think if we really need it for any reason.


# Contributors/Changelog connections
Connecting changes to contributors: I guess this is an interesting idea, but at the moment we're not showing this to user in any way and afaik we're not planning to. But here I guess we can disscuss this on the mobile weekly, but imo we don't need it. Again if you want to store this info for some reason, I guess I don't consider this to be a problem, but not sure if we're gonna use it.

_[MOBILE TEAM DISCUSSION NEEDED]: connecting contributors to changelog changes_


On the other hand we're planning on introducing multiple tabs in the "About us" team view - to show different teams for different versions. Not sure if this was the thing you had in mind here?

But here we're not interested in developer-change connection, nor in developer-version. We're only interested in developer-milestone connection. The team tabs will prolly include milestones and we would really want to have a very custom control on the people and versions that we have there and connecting this to the changelog domain is pretty useless imo.

**UPDATE: a person can actually change his title between milestones - so you need to handle this too, I guess creating new contributor instances every milestone is the simplest option and it's pretty easy and straightforward and gives us full customization capabilities. Unless you have better idea, I'm open for discussion - not sure if you even had this use-case/feature in mind when you connected contributors to changes.**

# Changelog
1. change types: I don't think we're gonna use anything other than `fix` and `feature` - but I guess you can do it as a separate table just for the future-proofness, but if this is supposed to make any sense, then we need some "label" short text field that we'll show in the mobile side.
UI reference here:
![Image](https://github.com/user-attachments/assets/2e686802-e15e-41da-98a5-2c180d8bd045)


3. screenshots: here again we don't even have the full design of this feature, so a room for discussion is pretty big. Afaik we had been planning only screenshots assiosiated to the whole version, that would be shown in some carousel in the dialog, but we can consider screenshot to the changes i guess too. But to be honest, if we go this way this will probably be shown in the same carousel anyway. But I guess we can add some tag then? Personally I would go with just simply screenshots connected to versions, but I have to discuss this with the team.


_[MOBILE TEAM DISCUSSION NEEDED]: screenshot to every change connection (imo skip)_

![Image](https://github.com/user-attachments/assets/cf4ebb48-1426-40f4-af58-5f9072b7d9c9)

_this button will show the carousel with screenshots, or at least that was the idea_


# Discussion
@czaja307 tbh the discussion is pretty big already, so I would create separate subissues for every developer's work and redistribute discussion to threads

**Comment by Matistan** [comment]
I can add authors and redactors for FAQ section

**Comment by Batory12** [comment]
I can do organizations

**Comment by Mikuu-252** [comment]
I can make department schema
