### ISSUE TITLE
chore/organizations schema

### ISSUE THREAD

**Issue by czaja307** [Solvro/backend-topwr#20]

**Comment by Batory12** [comment]
Here's what I came up with so far:
![Image](https://github.com/user-attachments/assets/2c5e7050-3c57-4d49-8bb3-c187cbdf742a)

**Comment by Batory12** [comment]
OK, corrected version
![Image](https://github.com/user-attachments/assets/70a5df74-07df-4c7e-a074-b1aa366ccae3)

**Comment by simon-the-shark** [comment]
We need the source to position the orgs on proper place

**Comment by Batory12** [comment]
In the original table there are also organisations that are not science clubs (like "samorząd"), and there is a field type for science clubs and other, which I think is OK, since science club is a type of student organisaton. So do we leave it like that or split into different tables?

**Comment by Batory12** [comment]
![Image](https://github.com/user-attachments/assets/88eff5b8-ec0a-42bf-b4fb-4c0aa51e9591)

**Comment by czaja307** [comment]
@simon-the-shark what do you think about the note? i'm quite sure that u use `type` in the app, but i'll need confirmation on this one

student organisation is a good choice, just change the pivot name to `student_organisations_student_organisation_tags` to match the naming convention

**Comment by simon-the-shark** [comment]
Yes, we use the types for filtering, but it's a separate section than tags

**Comment by Batory12** [comment]
![Image](https://github.com/user-attachments/assets/a37601b6-fd5a-4d71-ac38-96418d5c5294)
