### ISSUE TITLE
chore/authors, contibutors & changelog schemas

### ISSUE THREAD

**Issue by czaja307** [Solvro/backend-topwr#9]
Current version of the schema idea: (see edits for previous versions)
![Screenshot](https://github.com/user-attachments/assets/9481ca2f-4bde-4f66-ae56-e79f35beb1f1)
[Source file](https://github.com/user-attachments/files/17792663/ToPWR.contributors.changelogs.schema_2024-11-17T22_30_36.726Z.ddb.json)

**Comment by mini-bomba** [comment]
What the mobile app receives over the API does not need to match DB schema exactly. The backend can do basic processing of the data before serving it over the API.

About contributor roles:
- If you prefer to get a single string or a list of strings from the API, then that's possible with this DB schema.
- I added the roles table to prevent mistakes when entering the data and deduplicate the data stored in the database.
  - It won't be possible to misspell the role for just a single contributor. Either there's a misspelling for everyone who has the role, or for noone.
- We can add the milestone into the primary key for the `contributor_roles` table, which would make them scoped to a single milestone. 
  - While this would require the roles to be applied again (or copied) for each new milestone, it'd be much better than copying the whole contributor object for no reason.
  - This would also be a simple way to connect contributors to milestones
  - In this version, if we'd want to limit contributors to a single role per milestone, we could simply add an unique index on contribuor+milestone
  
Social links for contributors:
- If we decide that I'd be nice to allow multiple links of the same type, then I can edit the schema to allow that. Should be as simple as creating the usual integer autoincremented id primary key field for the table.

Contributor - change association:
- The topic of how to display this in the mobile app is of course for you (as the mobile team) to discuss. I just feel like crediting contributors for each change is the "usual" way to do it in an open-source project.
- If you decide that associating an author with each change does not make sense in the mobile app, but think that crediting all authors together in the version makes sense, then this could be achieved without any changes in to the DB schema.
  - The contributor to change links would stay in the backend as a way to reduce mistakes.
    - If everyone is properly credited for each change, then noone can be accidentally omitted or added to a version changelog.
  - The app can be served an aggregated list of all contributors that made a change that made it into a given version. It'd be just a single query.

**Comment by simon-the-shark** [comment]
So I've consulted my team and:

## Contributor - changes connection
So it's fair point about the open source projects, but in our case:
1. the changelog is more meant to be an info for the user and the github is more detailed changelog with specific changes and contributors
2. in the user facing changelog we really only want some general things, not to get into too much details and connecting this to one or even few users may be hard. E.g. one feature can be done by almost every person in the team, so presenting this to user is pretty useless and we want to avoid it
3. despite we're open source we really don't have any external contributors outside our core team at the moment
4. assuming we'll get some external contributor, we can always pay tribute to him, just by including him in the description. And the core topwr team will be eventually placed in the about us team section.

So basically we would rather have team members connected to some milestones or smth and changelog to be a separate thing that is meant to be a user facing notification.


## Contributor roles
You can go with what you've mentioned, but my only note is that this may be hard for the autogenerated admin to catch up nicely. But I guess you can discuss it and test it within your team. For the mobile side, this obviously doesn't make much difference. We just want to have the ability to have different roles in different versions

## Social links
After discussion we prolly want to have local icons anyway, so I would go with enum option here. But we're moving ordering logic to the backend endpoint for sure.

## Screenshots
we can go with what you've proposed originally. We'll make use of the change-screenshot assosiation too in some nice way

## Change types
Just as I've mentioned before, we can go with what you've proposed. I would only add "label" text field, unless the "name" was meant to be this short descriptive tag I've marked in the picture above

## Social links duplicates
I would prepare ourselves for the possibility to have duplicates, but prolly won't happen in the near future


Tell me what you think :) But this is more or less how the mobile team sees the matter

**Comment by mini-bomba** [comment]
Thanks for the feedback! I've taken in some of the suggestions, applied them to the schema and updated the files attached to the issue.

Changes made:
- Replaced all uses of VARCHAR with TEXT
- Renamed `change_types.name` to `change_types.label` as a clarification
- Removed the `change_authors` table
- Added a basic `milestones` table
- Added a `milestone` foreign key to the `contributor_roles` table and its primary key
- Edited the `contributor_social_links` to allow multiple links of the same type for the same contributor
- Replaced `versions.is_released` with a nullable `release_date` (date set = version released, date null = draft)

Questions remaining:
- For someone who's experienced with postgresql: is adding a new enum value to an existing column something painful, or can it be done easily?
- To the backend team: Will we have a centralized images table, or should we just store image URLs in the tables?

**Comment by chewmanji** [comment]
> Questions remaining:
> 
> * For someone who's experienced with postgresql: is adding a new enum value to an existing column something painful, or can it be done easily?

I'm not extremely experienced with postgresql but something like this should get it done:
```
ALTER TYPE enum_name
ADD VALUE [IF NOT EXISTS] 'new_value'
```
[ALTER TYPE docs](https://www.postgresql.org/docs/current/sql-altertype.html)

**Comment by mini-bomba** [comment]
I'm specifically asking for someone who has had some experience with enum values, as I'm worried that adding a new value might be expensive.
If someone is certain that adding a new value is trivial and quick, then we can use them in the schema. Otherwise I'd argue we should use tables, if in the future we decide to add a new value.

**Comment by czaja307** [comment]
you'll need to pay attention to define the enum as postres type, later when you'll be doing migrations  (it's like 4 lines of code straight from the documentation - https://lucid.adonisjs.com/docs/table-builder#enum--enu)
but if you do it this way you'll be able to extend enum as easily as @chewmanji said

**Comment by czaja307** [comment]
> * To the backend team: Will we have a centralized images table, or should we just store image URLs in the tables?

we haven't decided yet what photo service we'll use, but afaik most of them grant access to resources by some sort of URL or path

**Comment by czaja307** [comment]
some more comments:
1. social_link should be enum - it will improve the performance on the mobile end (change_type is fine as is)
2. i'll agree with @simon-the-shark on the matter of linking authors and changes together, i just don't see need for it - if someone wants to check details about contribution they can visit github, in the mobile app there is no need to merge these two functionalities together
3. i don't think we should keep info about milestones (they are more inside info for our project) - users should get only informations about versions imo
4. the contibuteor_roles table looks fine to me
